<cfif structKeyExists(Urun,"REFERENCEDOCUMENT") AND  len(Urun.REFERENCEDOCUMENT.URL)>
   
   <cfquery name="ins" datasource="#dsn1#">
        INSERT INTO PRODUCT_REFERENCE_DOCUMENTS_PARTNER  (DOCUMENT_URL,DOCUMENT_NAME,DOCUMENT_INFO,PRODUCT_ID) 
        VALUES ('#Urun.REFERENCEDOCUMENT.URL#','#Urun.REFERENCEDOCUMENT.NAME#','#Urun.REFERENCEDOCUMENT.REFERENCEDOCUMENTQUALIFIER#',#PBS_PRODUCT_ID#)
    </cfquery>
</cfif>